package com.schoolmanagement.schoolmanagementwebsite.enums;

public enum TeacherDesignation {
    
                 
   ADMIN_MANAGER,
HR_MANAGER,
ADMIN_ASSISTANT,
CLERICAL_ASSISTANT,
RECEPTIONIST,
OFFICE_EXECUTIVE,
DATA_ENTRY_OPERATOR,
ACADEMIC_COORDINATOR,
DISCIPLINE_COORDINATOR,
EXAM_COORDINATOR,
SENIOR_LIBRARIAN,
ASSISTANT_LIBRARIAN,
PEON,
CLEANER,
DRIVER,
SECURITY_GUARD,
BUS_CONDUCTOR,
PHYSICAL_EDUCATION_TEACHER,
SPORTS_COACH,
YOGA_INSTRUCTOR,
PRINCIPAL,
TRAINED_GRADUATE_TEACHER,
POST_GRADUATE_TEACHER,
PRIMARY_TEACHER,
SUBJECT_TEACHER,
COMPUTER_TEACHER,
VICE_PRINCIPAL
}
